version: '3.4'
services:
  linux-arm64:
    build: 
      context: .
      dockerfile: Dockerfile.linux
    platform: linux/arm64/v8
  linux-amd64:
    build: 
      context: .
      dockerfile: Dockerfile.linux
      args: 
      - FAISS_OPTIMIZATION=avx2
    platform: linux/amd64

